### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by treythomas123**
Took a stab at an initial implementation for this. Currently just a wrapper for umzug, making the setup easier than using umzug directly.

### CODE REVIEW

**Comment by janmeier** [comment]
Thanks, and congratulations - you now have push access to this repo, since you are the first to put some actual code into it ;)

(sorry if you got a lot of confusing emails, tooking me a bit to figure out github's new permissions system ;) )

**Comment by sdepold** [comment]
> Thanks, and congratulations - you now have push access to this repo, since you are the first to put some actual code into it ;)

:clap:

**Comment by treythomas123** [comment]
Awesome, thanks!

**Comment by treythomas123** [comment]
Also just published this on NPM and added both of you as collaborators :)

**Comment by sdepold** [comment]
:clap:

**Pull request merged**
